Update Recovery Build.yml

diff --git a/.github/workflows/Recovery Build.yml b/.github/workflows/Recovery Build.yml
--- a/.github/workflows/Recovery Build.yml
+++ b/.github/workflows/Recovery Build.yml
@@ -150,6 +150,18 @@ jobs:
       run: repo sync -j4 --force-sync
       working-directory: workspace
 
+    - name: Patch missing libgflags for snapuserd
+      run: |
+        cd system/core/fs_mgr/libsnapshot || exit 0
+        if [ ! -d ../../../external/gflags ]; then
+          echo "🔧 Cloning missing libgflags..."
+          cd ../../../external
+          git clone https://android.googlesource.com/platform/external/gflags gflags
+          cd -
+        fi
+        echo "✅ libgflags patched successfully."
+      working-directory: ${{ steps.pwd.outputs.workspace-folder }}
+
     - name: Clone Device Tree
       run: |
         rm -rf ./${{ github.event.inputs.DEVICE_PATH }}
